### cosmetic world map text
init -1 python in STR_WMAP:
    MAP_OF_ALDERAY = _("Alderay")
    LAKE_PEACING = _("Lake Peacing")
    DROSMERE_ESTATE = _("Drosmere Estate")
    FORT_DWAR = _("Fort Dwar")
    NEWYARK = _("Newyark")
    KINGDOM_OF_ANGMURUS = _("Kingdom of Angmurus")
    THE_BLACK_OCEAN = _("The Black Ocean")
    DRASMORE_ISLANDS = _("Drasmore Islands")
    NUBARIAN_TRIBELANDS = _("Nubarian Tribelands")
    CITY_OF_HAMUN = _("Free City of Hamun")
    KINGDOM_OF_INMA = _("Kingdom of Inma")
    BAY_OF_VALAR = _("Bay of Valar")
    THE_FREE_SEA = _("The Free Sea")
    THE_FORT_OF_BONES = _("The Fort of Bones")
    ARGONES_REST = _("Argones Rest")
    DAVOS_VILLAGE = _("Davos Village")
    VILLAGE_OF_IRISLOW = _("Village of Irislow")
    THE_RIVER_MAR = _("The river Mar")
    PULMAR_VILLAGE = _("Pulmar Village")
    FREEMAN_TOWN = _("Freeman Town")
    GERANO = _("Gerano")
    THE_BLACK_KEEP = _("The Black Keep")
    FORT_OF_SHADOWS = _("Fort of Shadows")
    ERIVA_VILLAGE = _("Eriva Village")
    FORT_ROOK = _("Fort Rook")