# TODO: Translation updated at 2026-07-01 11:57

translate ptBR strings:

    # game/engine/tutorial_popups_aio.rpy:40
    old "Welcome to Parasite Black!\n\nTutorial pop-ups such as this one will accompany you throughout the game.\n\nBefore you begin your journey, you must first confirm or change your character's {i}starting attributes{/i} and name.\n\nTake your time to explore what each attribute affects by hovering over it. You can always revert your changes to default.\n\nAs the game is still in-development, alot of the underlying mechanics are still undergoind big design overhauls.\n\nThese tutorial pop-ups can be disabled in the options menu."
    new "Bem-vindo a Parasite Black!\n\nPop-ups de tutorial como este vão te acompanhar ao longo do jogo.\n\nAntes de começar sua jornada, você deve primeiro confirmar ou alterar os {i}atributos iniciais{/i} e o nome do seu personagem.\n\nLeve o tempo que precisar para explorar o que cada atributo afeta passando o mouse sobre ele. Você sempre pode reverter suas alterações para o padrão.\n\nComo o jogo ainda está em desenvolvimento, muitas das mecânicas subjacentes ainda estão passando por grandes reformulações de design.\n\nEstes pop-ups de tutorial podem ser desativados no menu de opções."

    # game/engine/tutorial_popups_aio.rpy:41
    old "As a member of the Adventurers Guild, you now have access to the Guild's quest board.\n\nYou can click the quest board at any time of day to explore quests available for your Adventurer rank.\n\nCompleting each quest once will let you advance your rank by unlocking a more challenging, special quest.\n\nCurrently though, {i}only first tier of quests is implemented.{/i}\n\nEach quest will reappear on the board a few days after it is completed, but the experience reward will only be granted once."
    new "Como membro da Guilda dos Aventureiros, agora você tem acesso ao quadro de missões da Guilda.\n\nVocê pode clicar no quadro de missões a qualquer hora do dia para explorar as missões disponíveis para seu nível de Aventureiro.\n\nCompletar cada missão uma vez permitirá que você avance de nível ao desbloquear uma missão especial mais desafiadora.\n\nAtualmente, porém, {i}apenas o primeiro nível de missões está implementado.{/i}\n\nCada missão reaparecerá no quadro alguns dias após ser concluída, mas a recompensa de experiência será concedida apenas uma vez."

    # game/engine/tutorial_popups_aio.rpy:42
    old "You have gained access to an extra skill tree: {b}Parasite Skills{/b}.\n\nThese battle skills can only be used in a transformed state. You and Markus will earn one Parasite skill point each level, starting from level 4."
    new "Você ganhou acesso a uma árvore de habilidades extra: {b}Habilidades do Parasita{/b}.\n\nEssas habilidades de batalha só podem ser usadas no estado transformado. Você e Markus ganharão um ponto de habilidade do Parasita a cada nível, a partir do nível 4."

    # game/engine/tutorial_popups_aio.rpy:43
    old "You are now free to explore the world of Alderay.\n\nA globe icon can be found on a suitable location to initiate travel to a different location.\n\nYou can also open map screen (x) to explore the world map.\n\nIf you ever feel lost, you can find your currently active quests or important notes in the 'journal' screen.\n\nGood luck and have fun!"
    new "Agora você está livre para explorar o mundo de Alderay.\n\nUm ícone de globo pode ser encontrado em um local adequado para iniciar viagem para um local diferente.\n\nVocê também pode abrir a tela do mapa (x) para explorar o mapa-múndi.\n\nSe você se sentir perdido, pode encontrar suas missões ativas ou notas importantes na tela do 'diário'.\n\nBoa sorte e divirta-se!"

    # game/engine/tutorial_popups_aio.rpy:44
    old "The game time will now progress with every action you take, except for navigating the user interface.\n\nYou can use the time tracker (upper left) to tell current time.\n\nSome events in the game are dependent on time: if you are caught wandering around the fort at night, there will be consequences.\n\nOutside of narrative sections, you will often be able to skip time by {i}waiting (t).{/i}"
    new "O tempo do jogo agora avançará com cada ação que você realizar, exceto ao navegar pela interface do usuário.\n\nVocê pode usar o rastreador de tempo (canto superior esquerdo) para ver a hora atual.\n\nAlguns eventos no jogo dependem do horário: se você for pego vagando pelo forte à noite, haverá consequências.\n\nFora das seções narrativas, você frequentemente poderá pular o tempo {i}esperando (t).{/i}"

    # game/engine/tutorial_popups_aio.rpy:45
    old "Combat in the game is turn-based. In this exercise, you are to fight markus using simple {i}basic attacks{/i}.\n\nRegardless of their other skills or energy levels, any character in the game has a {i}basic attack{/i}.\n\nSelect the basic attack on the character panel, lower side of the screen and click Markus to attack him.\n\nYou are not required to win and will be able to repeat the exercise if you want to."
    new "O combate no jogo é por turnos. Neste exercício, você deve lutar contra Markus usando {i}ataques básicos{/i} simples.\n\nIndependentemente de suas outras habilidades ou níveis de energia, qualquer personagem no jogo tem um {i}ataque básico{/i}.\n\nSelecione o ataque básico no painel do personagem, na parte inferior da tela, e clique em Markus para atacá-lo.\n\nVocê não precisa vencer e poderá repetir o exercício se quiser."

    # game/engine/tutorial_popups_aio.rpy:46
    old "In this exercise, practice using your combat skills. Both you and Markus will also have a healing item to use.\n\nMost combat skills cost energy (the green bar) to use.\n\nYour energy is restored automatically each turn.\n\nTo use a skill, open up a 'skills' sub-menu on your character panel and select a skill in question, then select a target you want to use it on.\n\nItems are used in a similar way, from their corresponding sub-menu.\n\nUsing an item {i}does not end your turn{/i}, and you can use as many items per turn as you wish.\n\nAs in previous exercise, you are not required to win and will be able to repeat the exercise if you want to."
    new "Neste exercício, pratique o uso de suas habilidades de combate. Tanto você quanto Markus também terão um item de cura para usar.\n\nA maioria das habilidades de combate custa energia (a barra verde) para usar.\n\nSua energia é restaurada automaticamente a cada turno.\n\nPara usar uma habilidade, abra o submenu 'habilidades' no painel do seu personagem e selecione a habilidade em questão, depois selecione o alvo em que deseja usá-la.\n\nItens são usados de forma semelhante, a partir do submenu correspondente.\n\nUsar um item {i}não encerra seu turno{/i}, e você pode usar quantos itens por turno quiser.\n\nComo no exercício anterior, você não precisa vencer e poderá repetir o exercício se quiser."

    # game/engine/tutorial_popups_aio.rpy:47
    old "In this exercise, you will be paired up with another recruit as a {i}combat team{/i}.\n\nYou will be fighting against Markus paired up with another recruit.\n\nThe two extra scouts {i}have other skills{/i} than you and Markus.\n\nAs your turn begins, you can click a character to select them. As you decide on their action and execute it, their turn will end, allowing other characters to act.\n\nYou do not have to claim victory and will be able to repeat the exercise if you want to."
    new "Neste exercício, você será emparelhado com outro recruta como uma {i}equipe de combate{/i}.\n\nVocê lutará contra Markus emparelhado com outro recruta.\n\nOs dois batedores extras {i}têm outras habilidades{/i} além das suas e de Markus.\n\nQuando seu turno começar, você pode clicar em um personagem para selecioná-lo. Conforme você decide a ação dele e a executa, o turno dele terminará, permitindo que outros personagens ajam.\n\nVocê não precisa conquistar a vitória e poderá repetir o exercício se quiser."

    # game/engine/tutorial_popups_aio.rpy:48
    old "Kiara and Markus are now members of your {i}party.{/i}\nThey will accompany you on your mission and fight alongside you.\n\nYour party characters will automatically reach the same level you are, allowing you to {i}distribute their level-up points{/i}.\n\nYou can examine their character sheets in the 'characters' screen. In the 'inventory' screen, you can switch between party characters to examine or change their equipment."
    new "Kiara e Markus agora são membros do seu {i}grupo.{/i}\nEles vão te acompanhar na sua missão e lutar ao seu lado.\n\nSeus personagens do grupo automaticamente alcançarão o mesmo nível que você, permitindo que você {i}distribua os pontos de nível deles{/i}.\n\nVocê pode examinar as fichas deles na tela 'personagens'. Na tela 'inventário', você pode alternar entre personagens do grupo para examinar ou trocar os equipamentos deles."

    # game/engine/tutorial_popups_aio.rpy:49
    old "You have just recieved your first {i}quest{/i}. You can examine all the currently active quests using the {i}journal (q){/i} screen.\n\nThe journal lists all the currently active quests and your next objectives. Using your journal is a sure way to never get lost.\n\n{i}Inventory (e){/i} and {i}Relationships (r){/i} screens list your inventory and character relationships respectively."
    new "Você acabou de receber sua primeira {i}missão{/i}. Você pode examinar todas as missões ativas usando a tela {i}diário (q){/i}.\n\nO diário lista todas as missões atualmente ativas e seus próximos objetivos. Usar seu diário é uma maneira segura de nunca se perder.\n\nAs telas {i}Inventário (e){/i} e {i}Relacionamentos (r){/i} listam seu inventário e os relacionamentos dos personagens, respectivamente."

    # game/engine/tutorial_popups_aio.rpy:50
    old "You have reached a new {i}experience level.{/i}\n\nYou can now open the 'characters' screen to distribute your {i}attribute and skill points{/i}. Your distribution of points will only apply if you hit 'confirm'."
    new "Você alcançou um novo {i}nível de experiência.{/i}\n\nAgora você pode abrir a tela 'personagens' para distribuir seus {i}pontos de atributo e habilidade{/i}. Sua distribuição de pontos só será aplicada se você clicar em 'confirmar'."

    # game/engine/tutorial_popups_aio.rpy:51
    old "With this level-up, you have earned a perk point.\nPerks allow your parasite to develop certain unique abilities.\n\nPerk points are earned every 3 levels, starting from level 4.\nYou can find the new perks tab in the 'characters' screen."
    new "Com este aumento de nível, você ganhou um ponto de vantagem.\nVantagens permitem que seu parasita desenvolva certas habilidades únicas.\n\nPontos de vantagem são ganhos a cada 3 níveis, a partir do nível 4.\nVocê pode encontrar a nova aba de vantagens na tela 'personagens'."

    # game/engine/tutorial_popups_aio.rpy:52
    old "You have just earned some {i}experience points{/i}.\n\nIn Parasite Black, experience is earned mainly by completing quests and {i}unlocking lewd scenes{/i}. Fighting only awards small amounts of experience, and only {i}once for each unique enemy match-up{/i} you encounter.\n\nYou can track your progress to the next experience level in your 'equipment' screen."
    new "Você acabou de ganhar alguns {i}pontos de experiência{/i}.\n\nEm Parasite Black, a experiência é ganha principalmente completando missões e {i}desbloqueando cenas eróticas{/i}. Lutar concede apenas pequenas quantidades de experiência, e apenas {i}uma vez para cada combinação única de inimigos{/i} que você encontrar.\n\nVocê pode acompanhar seu progresso até o próximo nível de experiência na tela 'equipamento'."

