init -1 python in AI_TAGS:
    _constant = True

    DEAL_PHYS_DAMAGE = 0

    FAVOURED_HIGHER_AGI_THAN_TARGETS = 1
    FAVOURED_HIGHER_DEX_THAN_TARGETS = 2

    REMOVE_DEBUFFS_ON_TARGET = 3
    EFFECT_SCALES_WITH_AMOUNT_OF_DEBUFFS_ON_TARGET = 4

    REMOVE_BUFFS_ON_TARGET = 5
    EFFECT_SCALES_WITH_AMOUNT_OF_BUFFS_ON_TARGET = 6

    STRONGER_ON_BURNING_ENEMY = 7
    IGNORES_ENEMY_DODGE = 8
    FAVOURED_HIGHEST_DODGE = 9

    IGNORES_ENEMY_ARMOR = 10

    HEAL_SELF = 11
    HEAL_TARGET = 12

    FAVOURED_LAST_HIT = 13

    FAVOURED_HIGH_OWN_HP_RATIO = 14
    FAVOURED_HIGH_OWN_ENERGY_RATIO = 15

    FAVOURED_LOW_OWN_ENERGY_RATIO = 16
    FAVOURED_LOW_TARGET_ENERGY = 17

    FAVOURED_LOWER_TARGET_HP_RATIO = 18

    RAISE_TARGET_PHYS_DAMAGE_RESISTANCE = 19
    RAISE_OWN_PHYS_DAMAGE_RESISTANCE = 20

    TAUNT_TARGET = 21

    ONLY_IF_ALLIES_EXIST = 22

    INCREASE_SELF_DAMAGE = 23

    GAIN_TURN = 24