init python:
    static_item_defs["champion_armor"] = {
        "name": _("Champion armor"),
        "plural": _("Champion armor"),
        "desc": _("Stunning armor radiating power... Simply looking at it gives a sense of something holy."),
        "Armor": 13,
        "icon": "dlc/Quests/Arda_Quest/Arda/PB_Icon_LightArmor_Chest.webp",
        "grants_skill":"Summon1",
        "eqp_slots": EQP_SLOTS.CHEST,
        "value_per_unit": 35000,
        "cannot_lose": True,
        "cant_sell_msg": _("For some reason... I cannot bring myself to part with it..."),
        "shop_category": "armor",
        "sort_order": 40,
    }
    static_item_defs["star_bringer"] = {
        "name": _("Star Bringer"),
        "plural": _("Star Bringer"),
        "desc": _("A perfect blade. The new gods' magecraft is etched into the very soul of the sword itself..."),
        "Damage": 19,
        "add_attr_dex":2,
        "add_attr_end":1,
        "battle_perma_effects":["star_bringers_stealmanastrike"],
        "icon": "dlc/Quests/Arda_Quest/Arda/PB_Icon_LightArmor_Weapon.webp",
        "eqp_slots": EQP_SLOTS.HANDS,
        "value_per_unit": 50000,
        "cannot_lose": True,
        "cant_sell_msg": _("For some reason... I cannot bring myself to part with it..."),
        "shop_category": "weapon",
        "sort_order": 30,
    }