define ARDA = Character("ARDA")
define MALAKAI = Character("MALAKAI")

label test_script2: 
#Malakai armor DLC
#IMPLEMENTATION: One-time scene. Available after completing 'Two Emperors'. Auto-triggers when entering the player's bedroom.
"Entering my room, my eyes were drawn immediately to the strange, black envelope placed carefully on my bed."
"The envelope was expensive, scented with lavender, with a red seal on the back marked M.B. I carefully opened it to read the letter inside."
"{i}You are cordially invited to the Cathedral of Dreams... in your dreams. This invitation cannot be refused.{/i}"
"I stared at the letter for the longest time, turning the page around to see if something was written on the back. There wasn't."
MC "(... Is this a joke?)"
REGINA @talk "What do you have there?"
MC @think "Did you put this here?"
"Stepping forward, she took the letter carefully from my hand, but recoiled at the touch."
REGINA @angry "... Where did you get that?"
MC @think "What? It was just on my bed."
REGINA @shock "Your bed?"
REGINA @angry "Burn it."
MC @shock "What, why?"
REGINA @sad "I... Never mind."
REGINA @sad "It just makes me uneasy, is all."
"[regina_ref] offered the faintest, uneasy smile."
REGINA @talk "I just don't like knowing how it got there, is all."
"Her eyes continued to stare at the letter still in my hand."
"She reached out suddenly, snapping it from my hands."
MC @angry "[regina_ref]!"
REGINA @smile "Not to worry! I'll just take care of that!"
"She hurried away to her room, slamming and bolting the door behind her."
MC "(... What in the world?)"
####
#New quest appears: Sweet dreams...
#Quest detail: Go to sleep: Quest descrip: A mysterious letter was found on my bed saying someone would contact me in my dreams... Surely this is a joke? - XP reward: 250
#IMPLEMENTATION: Start 'Sweet dreams...' here. Sleeping while this quest stage is active triggers the following scene.
"As I lay down on my bed and closed my eyes... I began to feel myself sink into it."
"The world slowly became black around me, and suddenly, there was an eerie silence... As though the world outside simply ceased to be."
"The bed was gone. I found myself standing in a starless realm of darkness, where red lightning boomed and cracked across the sky."
"Ahead... A great temple."
"Looking down, I was suddenly wearing... my armor?"
"My blade was at my side."
MC @shock "... How-"
#The voice is marked as ??? - The voice is Malakai
MALAKAI "Come."
MALAKAI "COMECOMECOME..."
"The great gates opened as I stepped towards them, revealing a grand cathedral beyond as the ghostly voice boomed."
"Overlapping voices, distorted, some fighting with each other as though they were echoes that refused to agree with themselves."
MALAKAI "PROPHET."
MALAKAI "WAYWARD SON."
MALAKAI "KEY."
MALAKAI "MINE, NOT HIS."
MALAKAI "DEVOUR THE GODS."
MALAKAI "TRAITOR, TRAITOR, TRAITOR."
MALAKAI "EMPIRES... CHAINS..."
MALAKAI "GODS NOT TO RULE, THE CYCLE BROKEN."
"A voice violently snapped back, causing the cathedral-like windows to shatter."
MALAKAI "LIAR... THE CHAIN IS IN YOUR HAND!"
"The voice drew in a breath, and the whole cathedral seemed to bend and breathe in with it as all the voices spoke as one."
MALAKAI "FREEEEEEDOM."
MALAKAI "CHAINS UPON GODS. CHAINS UPON MEN."
MALAKAI "I SHALL BREAK THEM ALL."
"A chill ran down my spine as I reached for my blade in the dream, still looking for whoever might answer."
MC @shock "WHO IS THERE?"
MC @angry "ANSWER ME!"
"The voice laughed, answering all at once in a dozen conflicting voices."
MALAKAI "PROVE,PROVE,PROVE."
MALAKAI "MINE, MINE, MINE."
"The ground seemed to coalesce with black smoke, warping and twisting into the shape of some colossal beast."
MALAKAI "NO TEETH. NO CLAW."
MALAKAI "FREEDOM DEMANDS STRENGTH."
MALAKAI "PROVE."
"Its eyes were covered in a thick bandage, with an enormous blade in its hands as it snarled towards me!"
#IMPLEMENTATION: Unique battle encounter against the void horror. Parasite transformation is disabled for this fight. Victory continues directly to the wake-up scene.
"With a desperate swing of my blade, the smoke beast vanished beneath it with a howl."
MC @shock "{i}*Huff* *Huff*{/i}"
MC @shock "SHOW YOURSELF!"
"The voice doesn't answer; the very cathedral itself falls deathly silent."
"The walls begin to buckle, and all at once, the floor opens up beneath my feet as I fall... and fall... and fall."
#The player wakes up
MC @shock "...!"
"Sweat poured from me as I looked down towards my trembling hands."
"Was that really just a dream? It had felt so-"
"There, in front of my bed, now sat a black chest that was not there before."
"It looked... wrong... Like it had forced its way into a place where it didn't belong."
"Just looking at it made me feel uneasy."
"I stared at it for the longest time... and carefully moved forward to open it."
"Inside, carefully laid on a velvet interior... Armor... and a sword."
MC @shock "I... This can't be real."
"Inside, a small letter was carefully folded."
"{i}He has felt you now. Not seen you. Not yet. When he reaches for you, remember what you learned tonight. - M.B{/i}"
#IMPLEMENTATION: Grant Void Armor and Shadowreach, complete 'Sweet dreams...', and award 250 XP. Both reward items are permanently unsellable.
#Armor - 'Void Armor' - Armor description: Powerful, beautifully crafted armor reeking of old god magecraft... Whatever being made this, did so to give it to their champion... Value: 35000 (The armor cannot be sold - if player tries in a shop circling over it simply reads 'For some reason... I cannot bring myself to part with it...')
#Sword - 'Shadowreach' - Weapon description: A beautifully crafted blade resonating with the magecraft of the old gods... One can simply feel the power resonating through it by looking at it. Value 50000 (Cannot be sold, same as above)
################################################################################
#ARDA DLC ARMOR
#IMPLEMENTATION: One-time scene. Available after completing 'Two Emperors'. Auto-triggers while exploring Novaras.
#Bells ringing sfx
MC @think "... Do you hear that?"
MARKUS @think "Hear what?"
MC @talk "Those strange bells... I've never heard them before..."
MARKUS @think "Bells?"
MARKUS @smile "Perhaps you're finally losing it, friend."
"I felt the softest whisper in my ear, an invisible hand resting reassuringly on my shoulder."
#The voice is marked as ??? It is Arda
ARDA "{i}Come... follow my voice...{/i}"
ARDA "{i}To the garden.{/i}"
"I suddenly felt the strangest urge... to head to a church?"
#New quest appears: The ringing of the bells... Quest: After hearing some strange bells that no one else can hear... I feel compelled to head to a church for some reason? XP: 250
#IMPLEMENTATION: Start 'The ringing of the bells...' here. Entering the Novaras church while this quest stage is active triggers the following scene.
"... Entering into the halls of the church, once again, I heard the ringing of the bells."
MC @shock "There it is again!"
MC @shock "Markus, can't you hear-"
"As I turned to look towards him, he was gone."
MC @think "... Markus?"
"As I looked around, I saw that everyone had vanished."
MC @shock "... H-Hello?"
"Silence."
"And as I looked towards the windows and the door, only bright, white light was visible outside."
"It was as if the whole church had simply ceased to be where it was before... And was now somewhere else."
ARDA "Come... Follow my voice."
"The doors to the church opened once more to reveal a bright light, and with little other choice... I stepped through them."
"Stepping through, I found myself in the most beautiful of gardens..."
"And there, a great tree, its body seemingly made of space and twinkling with stars, called out once more like the gentlest whisper."
ARDA "I called... And you answered."
MC @think "... Who are you?"
ARDA "A friend."
ARDA "A voice."
ARDA "A dream."
"The whole garden seemed to move as one, its trees swaying in unison, and with it, the pleasant aroma of a warm summer's dew."
ARDA "He would make of you a weapon."
ARDA "He would make of you a tool."
ARDA "You are not a tool, you are not a weapon..."
ARDA "A flickering ember in the dark is no less beautiful because its light does not burn forever."
MC "I don't... I don't understand."
MC "Who would make me a weapon? Who would-"
ARDA "Duty. Honor. Courage."
ARDA "... Love."
"The tree glows brighter for a moment, as though a thousand thoughts and voices rush at once."
ARDA "IneverwantedwarIwantedtosavethemall."
ARDA "IHADTOLEADTHEMITWASTHEONLYWAY."
"The tree suddenly dims once more."
ARDA "... I am sorry."
ARDA "My mind... like glass shards pulled together in my hands."
ARDA "I... I need to give you something... something to-"
ARDA "TRIEDTRIEDTRIED."
ARDA "HOW MANY EMPIRES MUST I BUILD?"
ARDA "WHYWHYWHY CAN'T I SAVE THEM?"
"The voices begin to fight among themselves as the garden turns into a great forest, trees sprouting up and bending towards the great tree."
ARDA "RULE THEM FOREVER."
ARDA "LOVE THEM FOREVER."
ARDA "NEVER LET THEM MAKE MISTAKES AGAIN."
"The tree recoils from itself."
ARDA "NO."
ARDA "LET THEM GO."
"The tree shuddered violently, twisting itself."
ARDA "I CAN'T."
"Something begins to tear through, as though reality itself were paper."
"The voices once again begin to fight, one stern, one gentle, one afraid, and so on and so on."
ARDA "NONONONONO."
ARDA "PROVE HIMSELF."
ARDA "DON'T HARM HIM!"
ARDA "BREAK HIM AND REBUILD HIM SO HE CAN STAND BEFORE THE SHADOW!"
ARDA "HE DOESN'T NEED TO PROVE ANYTHING."
ARDA "EVERYONE MUST."
"As the voices argue with themselves, a being, white and strange, comes through the tear."
"Ghostly white, celestial, the figure smiles, drawing a terrible scythe from out of its chest."
"I reached for my sword almost instinctively as the figure smiled warmly, but something was wrong behind its eyes."
"It bowed, almost politely, though its eyes never left mine."
"Suddenly, it lunged forward to strike!"
#IMPLEMENTATION: Unique battle encounter against the void spirit. Parasite transformation is disabled for this fight. Victory returns the player directly to the church scene.
"With a swipe of my blade, the spirit began to dissipate, still smiling as she vanished into nothingness."
ARDA "I... I didn't mean for it to hurt you."
ARDA "I DID."
ARDA "I DIDN'T."
ARDA "I can't hold myself together."
ARDA "Go... Gift... Take it when you return..."
ARDA "Go... Go now..."
"A bright white light surrounded me, and once more... I was standing in the cathedral as though nothing had happened."
MARKUS @think "Are you alright?"
MC @shock "What?"
MARKUS @think "You just stared blankly ahead for a full minute."
MC @talk "I... What?"
MARKUS @talk "Are you suffering from a fever or something?"
MC @sad "I... I'm fine... Let's keep moving."
#Quest update: The voice said it left me a gift... But where?
#IMPLEMENTATION: Update the quest objective here. The next entry into the player's Novaras bedroom triggers the reward scene.
#Upon entering into the player's bedroom in his home in Novaras - scene auto triggers
"There, sitting awkwardly in the middle of my room, was a huge, ornate, white box."
"{i}...Not mine.{/i}"
"Warm beneath my fingers, with the faintest smell of rain on a summer day... Yet there wasn't a trace of moisture on it."
"As I nervously stepped towards it, the latch opened with ease."
"Inside, carefully arranged, were the most beautiful armor and blade I had ever seen."
"Simply looking at them, they radiated a sense of warmth..."
"Holding the blade in my hand, I could feel the surge of magecraft beneath my grip, a brief tingling sensation that even I, with no affinity for the craft, could sense."
"Was it crafted by the new gods?"
"I wasn't sure..."
"But I knew one thing."
"{i}It was mine now.{/i}"
#IMPLEMENTATION: Grant Champion Armor and Star bringer, complete 'The ringing of the bells...', and award 250 XP. Both reward items are permanently unsellable.
#Armor - 'Champion Armor' - Armor description: Stunning armor radiating power... Simply looking at it gives a sense of something holy." Value: 35000 (The armor cannot be sold - if player tries in a shop circling over it simply reads 'For some reason... I cannot bring myself to part with it...')
#Sword - 'Star bringer' - Weapon description: A perfect blade. The new gods' magecraft is etched into the very soul of the sword itself... Value 50000 (Cannot be sold, same as above)
return