# TODO: Translation updated at 2026-08-04 03:41

translate de strings:

    # game/engine/tutorial_popups_aio.rpy:40
    old "Welcome to Parasite Black!\n\nTutorial pop-ups such as this one will accompany you throughout the game.\n\nBefore you begin your journey, you must first confirm or change your character's {i}starting attributes{/i} and name.\n\nTake your time to explore what each attribute affects by hovering over it. You can always revert your changes to default.\n\nAs the game is still in-development, alot of the underlying mechanics are still undergoind big design overhauls.\n\nThese tutorial pop-ups can be disabled in the options menu."
    new "Welcome to Parasite Black!\n\nTutorial pop-ups such as this one will accompany you throughout the game.\n\nBefore you begin your journey, you must first confirm or change your character's {i}starting attributes{/i} and name.\n\nTake your time to explore what each attribute affects by hovering over it. You can always revert your changes to default.\n\nAs the game is still in-development, alot of the underlying mechanics are still undergoind big design overhauls.\n\nThese tutorial pop-ups can be disabled in the options menu."

    # game/engine/tutorial_popups_aio.rpy:41
    old "As a member of the Adventurers Guild, you now have access to the Guild's quest board.\n\nYou can click the quest board at any time of day to explore quests available for your Adventurer rank.\n\nCompleting each quest once will let you advance your rank by unlocking a more challenging, special quest.\n\nCurrently though, {i}only first tier of quests is implemented.{/i}\n\nEach quest will reappear on the board a few days after it is completed, but the experience reward will only be granted once."
    new "As a member of the Adventurers Guild, you now have access to the Guild's quest board.\n\nYou can click the quest board at any time of day to explore quests available for your Adventurer rank.\n\nCompleting each quest once will let you advance your rank by unlocking a more challenging, special quest.\n\nCurrently though, {i}only first tier of quests is implemented.{/i}\n\nEach quest will reappear on the board a few days after it is completed, but the experience reward will only be granted once."

    # game/engine/tutorial_popups_aio.rpy:42
    old "You have gained access to an extra skill tree: {b}Parasite Skills{/b}.\n\nThese battle skills can only be used in a transformed state. You and Markus will earn one Parasite skill point each level, starting from level 4."
    new "You have gained access to an extra skill tree: {b}Parasite Skills{/b}.\n\nThese battle skills can only be used in a transformed state. You and Markus will earn one Parasite skill point each level, starting from level 4."

    # game/engine/tutorial_popups_aio.rpy:43
    old "You are now free to explore the world of Alderay.\n\nA globe icon can be found on a suitable location to initiate travel to a different location.\n\nYou can also open map screen (x) to explore the world map.\n\nIf you ever feel lost, you can find your currently active quests or important notes in the 'journal' screen.\n\nGood luck and have fun!"
    new "You are now free to explore the world of Alderay.\n\nA globe icon can be found on a suitable location to initiate travel to a different location.\n\nYou can also open map screen (x) to explore the world map.\n\nIf you ever feel lost, you can find your currently active quests or important notes in the 'journal' screen.\n\nGood luck and have fun!"

    # game/engine/tutorial_popups_aio.rpy:44
    old "The game time will now progress with every action you take, except for navigating the user interface.\n\nYou can use the time tracker (upper left) to tell current time.\n\nSome events in the game are dependent on time: if you are caught wandering around the fort at night, there will be consequences.\n\nOutside of narrative sections, you will often be able to skip time by {i}waiting (t).{/i}"
    new "The game time will now progress with every action you take, except for navigating the user interface.\n\nYou can use the time tracker (upper left) to tell current time.\n\nSome events in the game are dependent on time: if you are caught wandering around the fort at night, there will be consequences.\n\nOutside of narrative sections, you will often be able to skip time by {i}waiting (t).{/i}"

    # game/engine/tutorial_popups_aio.rpy:45
    old "Combat in the game is turn-based. In this exercise, you are to fight markus using simple {i}basic attacks{/i}.\n\nRegardless of their other skills or energy levels, any character in the game has a {i}basic attack{/i}.\n\nSelect the basic attack on the character panel, lower side of the screen and click Markus to attack him.\n\nYou are not required to win and will be able to repeat the exercise if you want to."
    new "Combat in the game is turn-based. In this exercise, you are to fight markus using simple {i}basic attacks{/i}.\n\nRegardless of their other skills or energy levels, any character in the game has a {i}basic attack{/i}.\n\nSelect the basic attack on the character panel, lower side of the screen and click Markus to attack him.\n\nYou are not required to win and will be able to repeat the exercise if you want to."

    # game/engine/tutorial_popups_aio.rpy:46
    old "In this exercise, practice using your combat skills. Both you and Markus will also have a healing item to use.\n\nMost combat skills cost energy (the green bar) to use.\n\nYour energy is restored automatically each turn.\n\nTo use a skill, open up a 'skills' sub-menu on your character panel and select a skill in question, then select a target you want to use it on.\n\nItems are used in a similar way, from their corresponding sub-menu.\n\nUsing an item {i}does not end your turn{/i}, and you can use as many items per turn as you wish.\n\nAs in previous exercise, you are not required to win and will be able to repeat the exercise if you want to."
    new "In this exercise, practice using your combat skills. Both you and Markus will also have a healing item to use.\n\nMost combat skills cost energy (the green bar) to use.\n\nYour energy is restored automatically each turn.\n\nTo use a skill, open up a 'skills' sub-menu on your character panel and select a skill in question, then select a target you want to use it on.\n\nItems are used in a similar way, from their corresponding sub-menu.\n\nUsing an item {i}does not end your turn{/i}, and you can use as many items per turn as you wish.\n\nAs in previous exercise, you are not required to win and will be able to repeat the exercise if you want to."

    # game/engine/tutorial_popups_aio.rpy:47
    old "In this exercise, you will be paired up with another recruit as a {i}combat team{/i}.\n\nYou will be fighting against Markus paired up with another recruit.\n\nThe two extra scouts {i}have other skills{/i} than you and Markus.\n\nAs your turn begins, you can click a character to select them. As you decide on their action and execute it, their turn will end, allowing other characters to act.\n\nYou do not have to claim victory and will be able to repeat the exercise if you want to."
    new "In this exercise, you will be paired up with another recruit as a {i}combat team{/i}.\n\nYou will be fighting against Markus paired up with another recruit.\n\nThe two extra scouts {i}have other skills{/i} than you and Markus.\n\nAs your turn begins, you can click a character to select them. As you decide on their action and execute it, their turn will end, allowing other characters to act.\n\nYou do not have to claim victory and will be able to repeat the exercise if you want to."

    # game/engine/tutorial_popups_aio.rpy:48
    old "Kiara and Markus are now members of your {i}party.{/i}\nThey will accompany you on your mission and fight alongside you.\n\nYour party characters will automatically reach the same level you are, allowing you to {i}distribute their level-up points{/i}.\n\nYou can examine their character sheets in the 'characters' screen. In the 'inventory' screen, you can switch between party characters to examine or change their equipment."
    new "Kiara and Markus are now members of your {i}party.{/i}\nThey will accompany you on your mission and fight alongside you.\n\nYour party characters will automatically reach the same level you are, allowing you to {i}distribute their level-up points{/i}.\n\nYou can examine their character sheets in the 'characters' screen. In the 'inventory' screen, you can switch between party characters to examine or change their equipment."

    # game/engine/tutorial_popups_aio.rpy:49
    old "You have just recieved your first {i}quest{/i}. You can examine all the currently active quests using the {i}journal (q){/i} screen.\n\nThe journal lists all the currently active quests and your next objectives. Using your journal is a sure way to never get lost.\n\n{i}Inventory (e){/i} and {i}Relationships (r){/i} screens list your inventory and character relationships respectively."
    new "You have just recieved your first {i}quest{/i}. You can examine all the currently active quests using the {i}journal (q){/i} screen.\n\nThe journal lists all the currently active quests and your next objectives. Using your journal is a sure way to never get lost.\n\n{i}Inventory (e){/i} and {i}Relationships (r){/i} screens list your inventory and character relationships respectively."

    # game/engine/tutorial_popups_aio.rpy:50
    old "You have reached a new {i}experience level.{/i}\n\nYou can now open the 'characters' screen to distribute your {i}attribute and skill points{/i}. Your distribution of points will only apply if you hit 'confirm'."
    new "You have reached a new {i}experience level.{/i}\n\nYou can now open the 'characters' screen to distribute your {i}attribute and skill points{/i}. Your distribution of points will only apply if you hit 'confirm'."

    # game/engine/tutorial_popups_aio.rpy:51
    old "With this level-up, you have earned a perk point.\nPerks allow your parasite to develop certain unique abilities.\n\nPerk points are earned every 3 levels, starting from level 4.\nYou can find the new perks tab in the 'characters' screen."
    new "With this level-up, you have earned a perk point.\nPerks allow your parasite to develop certain unique abilities.\n\nPerk points are earned every 3 levels, starting from level 4.\nYou can find the new perks tab in the 'characters' screen."

    # game/engine/tutorial_popups_aio.rpy:52
    old "You have just earned some {i}experience points{/i}.\n\nIn Parasite Black, experience is earned mainly by completing quests and {i}unlocking lewd scenes{/i}. Fighting only awards small amounts of experience, and only {i}once for each unique enemy match-up{/i} you encounter.\n\nYou can track your progress to the next experience level in your 'equipment' screen."
    new "You have just earned some {i}experience points{/i}.\n\nIn Parasite Black, experience is earned mainly by completing quests and {i}unlocking lewd scenes{/i}. Fighting only awards small amounts of experience, and only {i}once for each unique enemy match-up{/i} you encounter.\n\nYou can track your progress to the next experience level in your 'equipment' screen."

