# TODO: Translation updated at 2026-08-04 03:41

translate de strings:

    # game/engine/tutorial_popups_aio.rpy:40
    old "Welcome to Parasite Black!\n\nTutorial pop-ups such as this one will accompany you throughout the game.\n\nBefore you begin your journey, you must first confirm or change your character's {i}starting attributes{/i} and name.\n\nTake your time to explore what each attribute affects by hovering over it. You can always revert your changes to default.\n\nAs the game is still in-development, alot of the underlying mechanics are still undergoind big design overhauls.\n\nThese tutorial pop-ups can be disabled in the options menu."
    new "Willkommen bei Parasite Black!\n\nTutorial-Pop-ups wie dieses werden dich während des gesamten Spiels begleiten.\n\nBevor du deine Reise beginnst, musst du zuerst die {i}Startattribute{/i} und den Namen deines Charakters bestätigen oder ändern.\n\nNimm dir Zeit, um herauszufinden, was jedes Attribut bewirkt, indem du mit der Maus darüber fährst. Du kannst deine Änderungen jederzeit auf die Standardwerte zurücksetzen.\n\nDa sich das Spiel noch in der Entwicklung befindet, werden viele der zugrunde liegenden Mechaniken derzeit noch großen Design-Überarbeitungen unterzogen.\n\nDiese Tutorial-Pop-ups können im Optionsmenü deaktiviert werden."

    # game/engine/tutorial_popups_aio.rpy:41
    old "As a member of the Adventurers Guild, you now have access to the Guild's quest board.\n\nYou can click the quest board at any time of day to explore quests available for your Adventurer rank.\n\nCompleting each quest once will let you advance your rank by unlocking a more challenging, special quest.\n\nCurrently though, {i}only first tier of quests is implemented.{/i}\n\nEach quest will reappear on the board a few days after it is completed, but the experience reward will only be granted once."
    new "Als Mitglied der Abenteurergilde hast du nun Zugriff auf das Auftragsbrett der Gilde.\n\nDu kannst jederzeit auf das Auftragsbrett klicken, um verfügbare Aufträge für deinen Abenteurerrang zu erkunden.\n\nWenn du jeden Auftrag einmal abgeschlossen hast, kannst du deinen Rang erhöhen, indem du einen schwierigeren, speziellen Auftrag freischaltest.\n\nDerzeit ist jedoch {i}nur die erste Stufe der Aufträge implementiert.{/i}\n\nJeder Auftrag erscheint einige Tage nach Abschluss wieder auf dem Brett, aber die Erfahrungsbelohnung wird nur einmal gewährt."

    # game/engine/tutorial_popups_aio.rpy:42
    old "You have gained access to an extra skill tree: {b}Parasite Skills{/b}.\n\nThese battle skills can only be used in a transformed state. You and Markus will earn one Parasite skill point each level, starting from level 4."
    new "Du hast Zugang zu einem zusätzlichen Fertigkeitsbaum erhalten: {b}Parasitenfähigkeiten{/b}.\n\nDiese Kampffähigkeiten können nur in verwandelter Form eingesetzt werden. Du und Markus erhalten ab Stufe 4 jeweils einen Parasitenfähigkeitspunkt pro Stufe."

    # game/engine/tutorial_popups_aio.rpy:43
    old "You are now free to explore the world of Alderay.\n\nA globe icon can be found on a suitable location to initiate travel to a different location.\n\nYou can also open map screen (x) to explore the world map.\n\nIf you ever feel lost, you can find your currently active quests or important notes in the 'journal' screen.\n\nGood luck and have fun!"
    new "Es steht dir nun frei, die Welt von Alderay zu erkunden.\n\nEin Globus-Symbol kann an geeigneten Orten gefunden werden, um eine Reise zu einem anderen Ort zu beginnen.\n\nDu kannst auch die Kartenansicht (x) öffnen, um die Weltkarte zu erkunden.\n\nFalls du dich jemals verloren fühlst, findest du deine aktuell aktiven Aufträge oder wichtige Notizen im 'Tagebuch'-Bildschirm.\n\nViel Glück und viel Spaß!"

    # game/engine/tutorial_popups_aio.rpy:44
    old "The game time will now progress with every action you take, except for navigating the user interface.\n\nYou can use the time tracker (upper left) to tell current time.\n\nSome events in the game are dependent on time: if you are caught wandering around the fort at night, there will be consequences.\n\nOutside of narrative sections, you will often be able to skip time by {i}waiting (t).{/i}"
    new "Die Spielzeit wird nun mit jeder deiner Aktionen voranschreiten, außer beim Navigieren in der Benutzeroberfläche.\n\nDu kannst die Zeitanzeige (oben links) verwenden, um die aktuelle Zeit abzulesen.\n\nEinige Ereignisse im Spiel sind zeitabhängig: Wenn du nachts beim Herumstreifen in der Festung erwischt wirst, hat das Konsequenzen.\n\nAußerhalb von Erzählabschnitten kannst du die Zeit oft durch {i}Warten (t){/i} überspringen."

    # game/engine/tutorial_popups_aio.rpy:45
    old "Combat in the game is turn-based. In this exercise, you are to fight markus using simple {i}basic attacks{/i}.\n\nRegardless of their other skills or energy levels, any character in the game has a {i}basic attack{/i}.\n\nSelect the basic attack on the character panel, lower side of the screen and click Markus to attack him.\n\nYou are not required to win and will be able to repeat the exercise if you want to."
    new "Der Kampf im Spiel ist rundenbasiert. In dieser Übung sollst du gegen Markus kämpfen und einfache {i}Basisangriffe{/i} einsetzen.\n\nUnabhängig von anderen Fertigkeiten oder Energiestufen hat jeder Charakter im Spiel einen {i}Basisangriff{/i}.\n\nWähle den Basisangriff auf dem Charakter-Panel im unteren Bildschirmbereich und klicke auf Markus, um ihn anzugreifen.\n\nDu musst nicht gewinnen und kannst die Übung wiederholen, wenn du möchtest."

    # game/engine/tutorial_popups_aio.rpy:46
    old "In this exercise, practice using your combat skills. Both you and Markus will also have a healing item to use.\n\nMost combat skills cost energy (the green bar) to use.\n\nYour energy is restored automatically each turn.\n\nTo use a skill, open up a 'skills' sub-menu on your character panel and select a skill in question, then select a target you want to use it on.\n\nItems are used in a similar way, from their corresponding sub-menu.\n\nUsing an item {i}does not end your turn{/i}, and you can use as many items per turn as you wish.\n\nAs in previous exercise, you are not required to win and will be able to repeat the exercise if you want to."
    new "In dieser Übung übst du den Einsatz deiner Kampffähigkeiten. Sowohl du als auch Markus haben einen Heilgegenstand zur Verwendung.\n\nDie meisten Kampffähigkeiten kosten Energie (der grüne Balken), um eingesetzt zu werden.\n\nDeine Energie wird jede Runde automatisch wiederhergestellt.\n\nUm eine Fertigkeit einzusetzen, öffne das Untermenü 'Fertigkeiten' in deinem Charakter-Panel, wähle die gewünschte Fertigkeit und dann ein Ziel aus, auf das du sie anwenden möchtest.\n\nGegenstände werden auf ähnliche Weise über ihr entsprechendes Untermenü verwendet.\n\nDie Verwendung eines Gegenstands {i}beendet deinen Zug nicht{/i}, und du kannst pro Zug so viele Gegenstände einsetzen, wie du möchtest.\n\nWie in der vorherigen Übung musst du nicht gewinnen und kannst die Übung wiederholen, wenn du möchtest."

    # game/engine/tutorial_popups_aio.rpy:47
    old "In this exercise, you will be paired up with another recruit as a {i}combat team{/i}.\n\nYou will be fighting against Markus paired up with another recruit.\n\nThe two extra scouts {i}have other skills{/i} than you and Markus.\n\nAs your turn begins, you can click a character to select them. As you decide on their action and execute it, their turn will end, allowing other characters to act.\n\nYou do not have to claim victory and will be able to repeat the exercise if you want to."
    new "In dieser Übung wirst du mit einem anderen Rekruten als {i}Kampfteam{/i} zusammengebracht.\n\nIhr kämpft gegen Markus, der mit einem anderen Rekruten zusammenarbeitet.\n\nDie beiden zusätzlichen Späher {i}verfügen über andere Fertigkeiten{/i} als du und Markus.\n\nWenn dein Zug beginnt, kannst du einen Charakter anklicken, um ihn auszuwählen. Sobald du seine Aktion auswählst und ausführst, endet sein Zug und andere Charaktere können handeln.\n\nDu musst nicht gewinnen und kannst die Übung wiederholen, wenn du möchtest."

    # game/engine/tutorial_popups_aio.rpy:48
    old "Kiara and Markus are now members of your {i}party.{/i}\nThey will accompany you on your mission and fight alongside you.\n\nYour party characters will automatically reach the same level you are, allowing you to {i}distribute their level-up points{/i}.\n\nYou can examine their character sheets in the 'characters' screen. In the 'inventory' screen, you can switch between party characters to examine or change their equipment."
    new "Kiara und Markus sind jetzt Mitglieder deiner {i}Gruppe.{/i}\nSie werden dich auf deiner Mission begleiten und an deiner Seite kämpfen.\n\nDeine Gruppenmitglieder erreichen automatisch dasselbe Level wie du, sodass du ihre {i}Level-up-Punkte verteilen{/i} kannst.\n\nDu kannst dir ihre Charakterbögen im Bildschirm 'Charaktere' ansehen. Im 'Inventar'-Bildschirm kannst du zwischen den Gruppenmitgliedern wechseln, um ihre Ausrüstung zu betrachten oder zu ändern."

    # game/engine/tutorial_popups_aio.rpy:49
    old "You have just recieved your first {i}quest{/i}. You can examine all the currently active quests using the {i}journal (q){/i} screen.\n\nThe journal lists all the currently active quests and your next objectives. Using your journal is a sure way to never get lost.\n\n{i}Inventory (e){/i} and {i}Relationships (r){/i} screens list your inventory and character relationships respectively."
    new "Du hast soeben deinen ersten {i}Auftrag{/i} erhalten. Du kannst alle derzeit aktiven Aufträge über den {i}Tagebuch (q){/i}-Bildschirm einsehen.\n\nDas Tagebuch listet alle aktuell aktiven Aufträge und deine nächsten Ziele auf. Die Verwendung deines Tagebuchs ist ein sicherer Weg, um nie die Orientierung zu verlieren.\n\n{i}Inventar (e){/i} und {i}Beziehungen (r){/i}-Bildschirme zeigen deinen Besitz bzw. die Charakterbeziehungen an."

    # game/engine/tutorial_popups_aio.rpy:50
    old "You have reached a new {i}experience level.{/i}\n\nYou can now open the 'characters' screen to distribute your {i}attribute and skill points{/i}. Your distribution of points will only apply if you hit 'confirm'."
    new "Du hast eine neue {i}Erfahrungsstufe{/i} erreicht.\n\nDu kannst jetzt den 'Charaktere'-Bildschirm öffnen, um deine {i}Attribut- und Fertigkeitspunkte{/i} zu verteilen. Deine Verteilung der Punkte wird nur übernommen, wenn du auf 'Bestätigen' klickst."

    # game/engine/tutorial_popups_aio.rpy:51
    old "With this level-up, you have earned a perk point.\nPerks allow your parasite to develop certain unique abilities.\n\nPerk points are earned every 3 levels, starting from level 4.\nYou can find the new perks tab in the 'characters' screen."
    new "Mit diesem Stufenaufstieg hast du einen Vorteilspunkt verdient.\nVorteile ermöglichen es deinem Parasiten, bestimmte einzigartige Fähigkeiten zu entwickeln.\n\nVorteilspunkte werden alle 3 Stufen ab Stufe 4 verdient.\nDu findest den neuen Vorteile-Tab im 'Charaktere'-Bildschirm."

    # game/engine/tutorial_popups_aio.rpy:52
    old "You have just earned some {i}experience points{/i}.\n\nIn Parasite Black, experience is earned mainly by completing quests and {i}unlocking lewd scenes{/i}. Fighting only awards small amounts of experience, and only {i}once for each unique enemy match-up{/i} you encounter.\n\nYou can track your progress to the next experience level in your 'equipment' screen."
    new "Du hast gerade einige {i}Erfahrungspunkte{/i} erhalten.\n\nIn Parasite Black erhältst du Erfahrung hauptsächlich durch das Abschließen von Quests und das {i}Freischalten von anzüglichen Szenen{/i}. Kämpfe bringen nur geringe Mengen an Erfahrung und nur {i}einmal pro einzigartiger Gegner-Kombination{/i}, der du begegnest.\n\nDu kannst deinen Fortschritt zur nächsten Erfahrungsstufe im 'Ausrüstungs'-Bildschirm verfolgen."

