# TODO: Translation updated at 2026-07-07 02:03

translate ptPT strings:

    # game/engine/tutorial_popups_aio.rpy:40
    old "Welcome to Parasite Black!\n\nTutorial pop-ups such as this one will accompany you throughout the game.\n\nBefore you begin your journey, you must first confirm or change your character's {i}starting attributes{/i} and name.\n\nTake your time to explore what each attribute affects by hovering over it. You can always revert your changes to default.\n\nAs the game is still in-development, alot of the underlying mechanics are still undergoind big design overhauls.\n\nThese tutorial pop-ups can be disabled in the options menu."
    new "Bem-vindo ao Parasite Black!\n\nJanelas de tutorial como esta acompanhar-te-ão ao longo do jogo.\n\nAntes de começares a tua jornada, tens primeiro de confirmar ou alterar os {i}atributos iniciais{/i} e o nome do teu personagem.\n\nToma o teu tempo para explorar o que cada atributo afeta passando o rato por cima. Podes sempre reverter as tuas alterações para o padrão.\n\nComo o jogo ainda está em desenvolvimento, muitas das mecânicas subjacentes ainda estão a passar por grandes revisões de design.\n\nEstas janelas de tutorial podem ser desativadas no menu de opções."

    # game/engine/tutorial_popups_aio.rpy:41
    old "As a member of the Adventurers Guild, you now have access to the Guild's quest board.\n\nYou can click the quest board at any time of day to explore quests available for your Adventurer rank.\n\nCompleting each quest once will let you advance your rank by unlocking a more challenging, special quest.\n\nCurrently though, {i}only first tier of quests is implemented.{/i}\n\nEach quest will reappear on the board a few days after it is completed, but the experience reward will only be granted once."
    new "Como membro da Guilda dos Aventureiros, agora tens acesso ao quadro de missões da Guilda.\n\nPodes clicar no quadro de missões a qualquer hora do dia para explorar as missões disponíveis para o teu nível de Aventureiro.\n\nCompletar cada missão uma vez permitir-te-á avançar o teu nível desbloqueando uma missão especial mais desafiante.\n\nAtualmente, porém, {i}apenas o primeiro nível de missões está implementado.{/i}\n\nCada missão reaparecerá no quadro alguns dias depois de ser completada, mas a recompensa de experiência só será concedida uma vez."

    # game/engine/tutorial_popups_aio.rpy:42
    old "You have gained access to an extra skill tree: {b}Parasite Skills{/b}.\n\nThese battle skills can only be used in a transformed state. You and Markus will earn one Parasite skill point each level, starting from level 4."
    new "Ganhaste acesso a uma árvore de habilidades extra: {b}Habilidades do Parasita{/b}.\n\nEstas habilidades de combate só podem ser usadas no estado transformado. Tu e Markus ganharão um ponto de habilidade do Parasita por cada nível, a partir do nível 4."

    # game/engine/tutorial_popups_aio.rpy:43
    old "You are now free to explore the world of Alderay.\n\nA globe icon can be found on a suitable location to initiate travel to a different location.\n\nYou can also open map screen (x) to explore the world map.\n\nIf you ever feel lost, you can find your currently active quests or important notes in the 'journal' screen.\n\nGood luck and have fun!"
    new "Agora és livre de explorar o mundo de Alderay.\n\nUm ícone de globo pode ser encontrado num local adequado para iniciar viagem para um local diferente.\n\nTambém podes abrir o ecrã do mapa (x) para explorar o mapa do mundo.\n\nSe alguma vez te sentires perdido, podes encontrar as tuas missões ativas ou notas importantes no ecrã do 'diário'.\n\nBoa sorte e diverte-te!"

    # game/engine/tutorial_popups_aio.rpy:44
    old "The game time will now progress with every action you take, except for navigating the user interface.\n\nYou can use the time tracker (upper left) to tell current time.\n\nSome events in the game are dependent on time: if you are caught wandering around the fort at night, there will be consequences.\n\nOutside of narrative sections, you will often be able to skip time by {i}waiting (t).{/i}"
    new "O tempo de jogo irá agora progredir com cada ação que tomares, exceto ao navegar na interface.\n\nPodes usar o indicador de tempo (canto superior esquerdo) para ver as horas.\n\nAlguns eventos no jogo dependem da hora: se fores apanhado a vaguear pelo forte à noite, haverá consequências.\n\nFora das secções narrativas, poderás muitas vezes passar o tempo {i}esperando (t).{/i}"

    # game/engine/tutorial_popups_aio.rpy:45
    old "Combat in the game is turn-based. In this exercise, you are to fight markus using simple {i}basic attacks{/i}.\n\nRegardless of their other skills or energy levels, any character in the game has a {i}basic attack{/i}.\n\nSelect the basic attack on the character panel, lower side of the screen and click Markus to attack him.\n\nYou are not required to win and will be able to repeat the exercise if you want to."
    new "O combate no jogo é por turnos. Neste exercício, vais lutar contra o Markus usando {i}ataques básicos{/i} simples.\n\nIndependentemente das suas outras habilidades ou níveis de energia, qualquer personagem no jogo tem um {i}ataque básico{/i}.\n\nSeleciona o ataque básico no painel do personagem, no lado inferior do ecrã, e clica no Markus para o atacar.\n\nNão és obrigado a vencer e poderás repetir o exercício se quiseres."

    # game/engine/tutorial_popups_aio.rpy:46
    old "In this exercise, practice using your combat skills. Both you and Markus will also have a healing item to use.\n\nMost combat skills cost energy (the green bar) to use.\n\nYour energy is restored automatically each turn.\n\nTo use a skill, open up a 'skills' sub-menu on your character panel and select a skill in question, then select a target you want to use it on.\n\nItems are used in a similar way, from their corresponding sub-menu.\n\nUsing an item {i}does not end your turn{/i}, and you can use as many items per turn as you wish.\n\nAs in previous exercise, you are not required to win and will be able to repeat the exercise if you want to."
    new "Neste exercício, pratica o uso das tuas habilidades de combate. Tanto tu como Markus também terão um item de cura para usar.\n\nA maioria das habilidades de combate custa energia (a barra verde) para usar.\n\nA tua energia é restaurada automaticamente a cada turno.\n\nPara usar uma habilidade, abre o sub-menu de 'habilidades' no teu painel de personagem e seleciona a habilidade em questão, depois seleciona o alvo no qual a queres usar.\n\nOs itens são usados de forma semelhante, a partir do seu sub-menu correspondente.\n\nUsar um item {i}não termina o teu turno{/i}, e podes usar quantos itens quiseres por turno.\n\nComo no exercício anterior, não és obrigado a vencer e poderás repetir o exercício se quiseres."

    # game/engine/tutorial_popups_aio.rpy:47
    old "In this exercise, you will be paired up with another recruit as a {i}combat team{/i}.\n\nYou will be fighting against Markus paired up with another recruit.\n\nThe two extra scouts {i}have other skills{/i} than you and Markus.\n\nAs your turn begins, you can click a character to select them. As you decide on their action and execute it, their turn will end, allowing other characters to act.\n\nYou do not have to claim victory and will be able to repeat the exercise if you want to."
    new "Neste exercício, serás emparelhado com outro recruta como uma {i}equipa de combate{/i}.\n\nVais lutar contra Markus emparelhado com outro recruta.\n\nOs dois batedores extra {i}têm outras habilidades{/i} além das tuas e do Markus.\n\nQuando o teu turno começar, podes clicar num personagem para o selecionar. Quando decidires a ação dele e a executares, o turno dele terminará, permitindo que outros personagens atuem.\n\nNão tens de conquistar a vitória e poderás repetir o exercício se quiseres."

    # game/engine/tutorial_popups_aio.rpy:48
    old "Kiara and Markus are now members of your {i}party.{/i}\nThey will accompany you on your mission and fight alongside you.\n\nYour party characters will automatically reach the same level you are, allowing you to {i}distribute their level-up points{/i}.\n\nYou can examine their character sheets in the 'characters' screen. In the 'inventory' screen, you can switch between party characters to examine or change their equipment."
    new "Kiara e Markus são agora membros do teu {i}grupo.{/i}\nEles acompanhar-te-ão na tua missão e lutarão ao teu lado.\n\nAs tuas personagens do grupo alcançarão automaticamente o mesmo nível que tu, permitindo-te {i}distribuir os seus pontos de subida de nível{/i}.\n\nPodes examinar as suas fichas de personagem no ecrã 'personagens'. No ecrã 'inventário', podes alternar entre personagens do grupo para examinar ou mudar o seu equipamento."

    # game/engine/tutorial_popups_aio.rpy:49
    old "You have just recieved your first {i}quest{/i}. You can examine all the currently active quests using the {i}journal (q){/i} screen.\n\nThe journal lists all the currently active quests and your next objectives. Using your journal is a sure way to never get lost.\n\n{i}Inventory (e){/i} and {i}Relationships (r){/i} screens list your inventory and character relationships respectively."
    new "Acabaste de receber a tua primeira {i}missão{/i}. Podes examinar todas as missões atualmente ativas usando o ecrã do {i}diário (q){/i}.\n\nO diário lista todas as missões atualmente ativas e os teus próximos objetivos. Usar o teu diário é uma forma segura de nunca te perderes.\n\nOs ecrãs de {i}Inventário (e){/i} e {i}Relacionamentos (r){/i} listam o teu inventário e relacionamentos com personagens, respetivamente."

    # game/engine/tutorial_popups_aio.rpy:50
    old "You have reached a new {i}experience level.{/i}\n\nYou can now open the 'characters' screen to distribute your {i}attribute and skill points{/i}. Your distribution of points will only apply if you hit 'confirm'."
    new "Alcançaste um novo {i}nível de experiência.{/i}\n\nAgora podes abrir o ecrã de 'personagens' para distribuir os teus {i}pontos de atributo e habilidade{/i}. A tua distribuição de pontos só se aplicará se clicares em 'confirmar'."

    # game/engine/tutorial_popups_aio.rpy:51
    old "With this level-up, you have earned a perk point.\nPerks allow your parasite to develop certain unique abilities.\n\nPerk points are earned every 3 levels, starting from level 4.\nYou can find the new perks tab in the 'characters' screen."
    new "Com este aumento de nível, ganhaste um ponto de vantagem.\nAs vantagens permitem que o teu parasita desenvolva certas habilidades únicas.\n\nPontos de vantagem são ganhos a cada 3 níveis, a partir do nível 4.\nPodes encontrar o novo separador de vantagens no ecrã de 'personagens'."

    # game/engine/tutorial_popups_aio.rpy:52
    old "You have just earned some {i}experience points{/i}.\n\nIn Parasite Black, experience is earned mainly by completing quests and {i}unlocking lewd scenes{/i}. Fighting only awards small amounts of experience, and only {i}once for each unique enemy match-up{/i} you encounter.\n\nYou can track your progress to the next experience level in your 'equipment' screen."
    new "Acabaste de ganhar alguns {i}pontos de experiência{/i}.\n\nEm Parasite Black, a experiência ganha-se principalmente ao completar missões e {i}desbloquear cenas eróticas{/i}. Combater concede apenas pequenas quantidades de experiência, e apenas {i}uma vez por cada confronto único com inimigos{/i} que encontrares.\n\nPodes acompanhar o teu progresso até ao próximo nível de experiência no ecrã de 'equipamento'."

