# TODO: Translation updated at 2026-06-09 21:50

translate tr strings:

    # game/engine/tutorial_popups_aio.rpy:40
    old "Welcome to Parasite Black!\n\nTutorial pop-ups such as this one will accompany you throughout the game.\n\nBefore you begin your journey, you must first confirm or change your character's {i}starting attributes{/i} and name.\n\nTake your time to explore what each attribute affects by hovering over it. You can always revert your changes to default.\n\nAs the game is still in-development, alot of the underlying mechanics are still undergoind big design overhauls.\n\nThese tutorial pop-ups can be disabled in the options menu."
    new "Parasite Black'e hoş geldiniz!\n\nBunun gibi eğitici açılır pencereler oyun boyunca size eşlik edecek.\n\nYolculuğunuza başlamadan önce, önce karakterinizin {i}başlangıç özelliklerini{/i} ve adını onaylamalı veya değiştirmelisiniz.\n\nHer özelliğin neyi etkilediğini, üzerine gelerek keşfetmek için zaman ayırın. Değişikliklerinizi her zaman varsayılana döndürebilirsiniz.\n\nOyun hala geliştirme aşamasında olduğu için, altta yatan mekaniklerin çoğu hala büyük tasarım revizyonlarından geçiyor.\n\nBu eğitici açılır pencereler seçenekler menüsünden devre dışı bırakılabilir."

    # game/engine/tutorial_popups_aio.rpy:41
    old "As a member of the Adventurers Guild, you now have access to the Guild's quest board.\n\nYou can click the quest board at any time of day to explore quests available for your Adventurer rank.\n\nCompleting each quest once will let you advance your rank by unlocking a more challenging, special quest.\n\nCurrently though, {i}only first tier of quests is implemented.{/i}\n\nEach quest will reappear on the board a few days after it is completed, but the experience reward will only be granted once."
    new "Maceracılar Loncası'nın bir üyesi olarak, artık Lonca'nın görev panosuna erişiminiz var.\n\nMaceracı rütbeniz için mevcut görevleri keşfetmek için günün herhangi bir saatinde görev panosuna tıklayabilirsiniz.\n\nHer görevi bir kez tamamlamak, daha zorlu, özel bir görevin kilidini açarak rütbenizi ilerletmenizi sağlayacak.\n\nŞu anda, {i}sadece ilk görev kademesi uygulandı.{/i}\n\nHer görev tamamlandıktan birkaç gün sonra panoda yeniden görünecek, ancak deneyim ödülü sadece bir kez verilecek."

    # game/engine/tutorial_popups_aio.rpy:42
    old "You have gained access to an extra skill tree: {b}Parasite Skills{/b}.\n\nThese battle skills can only be used in a transformed state. You and Markus will earn one Parasite skill point each level, starting from level 4."
    new "Ekstra bir beceri ağacına erişim kazandınız: {b}Parazit Becerileri{/b}.\n\nBu savaş becerileri sadece dönüşmüş halde kullanılabilir. Sen ve Markus, 4. seviyeden başlayarak her seviyede bir Parazit beceri puanı kazanacaksınız."

    # game/engine/tutorial_popups_aio.rpy:43
    old "You are now free to explore the world of Alderay.\n\nA globe icon can be found on a suitable location to initiate travel to a different location.\n\nYou can also open map screen (x) to explore the world map.\n\nIf you ever feel lost, you can find your currently active quests or important notes in the 'journal' screen.\n\nGood luck and have fun!"
    new "Artık Alderay dünyasını özgürce keşfedebilirsiniz.\n\nFarklı bir konuma seyahati başlatmak için uygun bir konumda bir küre simgesi bulunabilir.\n\nDünya haritasını keşfetmek için harita ekranını (x) da açabilirsiniz.\n\nEğer hiç kaybolmuş hissederseniz, şu anda aktif görevlerinizi veya önemli notlarınızı 'günlük' ekranında bulabilirsiniz.\n\nİyi şanslar ve iyi eğlenceler!"

    # game/engine/tutorial_popups_aio.rpy:44
    old "The game time will now progress with every action you take, except for navigating the user interface.\n\nYou can use the time tracker (upper left) to tell current time.\n\nSome events in the game are dependent on time: if you are caught wandering around the fort at night, there will be consequences.\n\nOutside of narrative sections, you will often be able to skip time by {i}waiting (t).{/i}"
    new "Oyun zamanı, kullanıcı arayüzünde gezinmek dışında, yaptığınız her eylemle ilerleyecektir.\n\nMevcut zamanı söylemek için zaman izleyiciyi (sol üst) kullanabilirsiniz.\n\nOyundaki bazı olaylar zamana bağlıdır: eğer gece kalenin etrafında dolaşırken yakalanırsanız, sonuçları olacaktır.\n\nAnlatı bölümlerinin dışında, {i}bekleyerek (t){/i} zamanı atlayabilirsiniz."

    # game/engine/tutorial_popups_aio.rpy:45
    old "Combat in the game is turn-based. In this exercise, you are to fight markus using simple {i}basic attacks{/i}.\n\nRegardless of their other skills or energy levels, any character in the game has a {i}basic attack{/i}.\n\nSelect the basic attack on the character panel, lower side of the screen and click Markus to attack him.\n\nYou are not required to win and will be able to repeat the exercise if you want to."
    new "Oyundaki savaş sıra tabanlıdır. Bu alıştırmada, basit {i}temel saldırılar{/i} kullanarak markus ile dövüşeceksiniz.\n\nDiğer becerileri veya enerji seviyeleri ne olursa olsun, oyundaki herhangi bir karakterin bir {i}temel saldırısı{/i} vardır.\n\nKarakter panelinde, ekranın alt tarafında temel saldırıyı seç ve ona saldırmak için Markus'a tıkla.\n\nKazanmak zorunda değilsin ve istersen alıştırmayı tekrarlayabileceksin."

    # game/engine/tutorial_popups_aio.rpy:46
    old "In this exercise, practice using your combat skills. Both you and Markus will also have a healing item to use.\n\nMost combat skills cost energy (the green bar) to use.\n\nYour energy is restored automatically each turn.\n\nTo use a skill, open up a 'skills' sub-menu on your character panel and select a skill in question, then select a target you want to use it on.\n\nItems are used in a similar way, from their corresponding sub-menu.\n\nUsing an item {i}does not end your turn{/i}, and you can use as many items per turn as you wish.\n\nAs in previous exercise, you are not required to win and will be able to repeat the exercise if you want to."
    new "Bu alıştırmada, savaş becerilerini kullanarak pratik yap. Hem senin hem de Markus'un kullanmak için bir iyileştirme eşyası da olacak.\n\nÇoğu savaş becerisi kullanmak için enerjiye (yeşil çubuk) mal olur.\n\nEnerjin her tur otomatik olarak yenilenir.\n\nBir beceriyi kullanmak için, karakter panelinde bir 'beceriler' alt menüsünü aç ve söz konusu beceriyi seç, sonra onu kullanmak istediğin bir hedefi seç.\n\nEşyalar benzer şekilde, karşılık gelen alt menülerinden kullanılır.\n\nBir eşya kullanmak {i}turunu sonlandırmaz{/i}, ve tur başına istediğin kadar eşya kullanabilirsin.\n\nÖnceki alıştırmada olduğu gibi, kazanmak zorunda değilsin ve istersen alıştırmayı tekrarlayabileceksin."

    # game/engine/tutorial_popups_aio.rpy:47
    old "In this exercise, you will be paired up with another recruit as a {i}combat team{/i}.\n\nYou will be fighting against Markus paired up with another recruit.\n\nThe two extra scouts {i}have other skills{/i} than you and Markus.\n\nAs your turn begins, you can click a character to select them. As you decide on their action and execute it, their turn will end, allowing other characters to act.\n\nYou do not have to claim victory and will be able to repeat the exercise if you want to."
    new "Bu alıştırmada, bir {i}savaş takımı{/i} olarak başka bir acemiyle eşleştirileceksin.\n\nBaşka bir acemiyle eşleştirilmiş Markus'a karşı dövüşeceksin.\n\nEkstra iki izci, sen ve Markus'tan {i}başka becerilere{/i} sahip.\n\nTurun başladığında, onları seçmek için bir karaktere tıklayabilirsin. Eylemlerine karar verip uyguladığında, turları sona erecek, diğer karakterlerin hareket etmesine izin verecek.\n\nZafer talep etmek zorunda değilsin ve istersen alıştırmayı tekrarlayabileceksin."

    # game/engine/tutorial_popups_aio.rpy:48
    old "Kiara and Markus are now members of your {i}party.{/i}\nThey will accompany you on your mission and fight alongside you.\n\nYour party characters will automatically reach the same level you are, allowing you to {i}distribute their level-up points{/i}.\n\nYou can examine their character sheets in the 'characters' screen. In the 'inventory' screen, you can switch between party characters to examine or change their equipment."
    new "Kiara ve Markus artık {i}partinin{/i} üyeleri.\nGörevinde sana eşlik edecek ve yanında savaşacaklar.\n\nParti karakterlerin otomatik olarak seninle aynı seviyeye ulaşacak, {i}seviye atlama puanlarını dağıtmana{/i} izin verecek.\n\nKarakter sayfalarını 'karakterler' ekranında inceleyebilirsin. 'Envanter' ekranında, ekipmanlarını incelemek veya değiştirmek için parti karakterleri arasında geçiş yapabilirsin."

    # game/engine/tutorial_popups_aio.rpy:49
    old "You have just recieved your first {i}quest{/i}. You can examine all the currently active quests using the {i}journal (q){/i} screen.\n\nThe journal lists all the currently active quests and your next objectives. Using your journal is a sure way to never get lost.\n\n{i}Inventory (e){/i} and {i}Relationships (r){/i} screens list your inventory and character relationships respectively."
    new "İlk {i}görevini{/i} az önce aldın. {i}Günlük (q){/i} ekranını kullanarak şu anda aktif olan tüm görevleri inceleyebilirsin.\n\nGünlük, şu anda aktif olan tüm görevleri ve sonraki hedeflerini listeler. Günlüğünü kullanmak asla kaybolmamanın kesin bir yoludur.\n\n{i}Envanter (e){/i} ve {i}İlişkiler (r){/i} ekranları sırasıyla envanterini ve karakter ilişkilerini listeler."

    # game/engine/tutorial_popups_aio.rpy:50
    old "You have reached a new {i}experience level.{/i}\n\nYou can now open the 'characters' screen to distribute your {i}attribute and skill points{/i}. Your distribution of points will only apply if you hit 'confirm'."
    new "Yeni bir {i}deneyim seviyesine{/i} ulaştın.\n\n{i}Öznitelik ve beceri puanlarını{/i} dağıtmak için 'karakterler' ekranını açabilirsin. Puan dağıtımın sadece 'onayla'ya bastığında uygulanacak."

    # game/engine/tutorial_popups_aio.rpy:51
    old "With this level-up, you have earned a perk point.\nPerks allow your parasite to develop certain unique abilities.\n\nPerk points are earned every 3 levels, starting from level 4.\nYou can find the new perks tab in the 'characters' screen."
    new "Bu seviye atlamayla, bir yetenek puanı kazandın.\nYetenekler, parazitinin belirli benzersiz yetenekler geliştirmesine izin verir.\n\nYetenek puanları, 4. seviyeden başlayarak her 3 seviyede bir kazanılır.\nYeni yetenekler sekmesini 'karakterler' ekranında bulabilirsin."

    # game/engine/tutorial_popups_aio.rpy:52
    old "You have just earned some {i}experience points{/i}.\n\nIn Parasite Black, experience is earned mainly by completing quests and {i}unlocking lewd scenes{/i}. Fighting only awards small amounts of experience, and only {i}once for each unique enemy match-up{/i} you encounter.\n\nYou can track your progress to the next experience level in your 'equipment' screen."
    new "Az önce biraz {i}deneyim puanı{/i} kazandın.\n\nParasite Black'te deneyim esas olarak görevleri tamamlayarak ve {i}müstehcen sahnelerin kilidini açarak{/i} kazanılır. Savaşmak sadece küçük miktarlarda deneyim verir, ve sadece karşılaştığın {i}her benzersiz düşman eşleşmesi için bir kez{/i}.\n\nBir sonraki deneyim seviyesine ilerlemeni 'ekipman' ekranında takip edebilirsin."

